# Generated by Django 4.2.2 on 2023-06-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_diplom', '0003_tarif_alter_phone_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarif',
            new_name='Tarifs',
        ),
    ]
