# Generated by Django 4.2.2 on 2023-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_diplom', '0004_rename_tarif_tarifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifs',
            name='description1',
            field=models.TextField(default='defalult description'),
        ),
    ]
