# Generated by Django 4.2.2 on 2023-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_diplom', '0005_tarifs_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifs',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarifs',
            name='description1',
            field=models.CharField(max_length=255),
        ),
    ]
